language: php

matrix:
  include:
    - php: 7.1
    - php: 7.1
      deps: low
    - php: 7.2
    - php: 7.2
      deps: low

before_script:
  - composer validate
  - if [[ $deps = low ]]; then composer update --prefer-lowest --prefer-stable; else composer update; fi

script:
  - ./bin/phpcs
  - ./bin/phpunit -vvv

