language: php

matrix:
  include:
    - php: 5.6
    - php: 5.6
      env: deps=low
    - php: 7.0
    - php: 7.1
    - php: 7.2

before_script:
  - composer validate
  - if [[ $deps = low ]]; then composer update --prefer-lowest --prefer-stable; else composer update; fi

script: ./bin/phpunit -vvv

